language: python
sudo: false
notifications:
  email: false
python:
- '3.6'
before_install:
- sudo apt-get -y install gcc libattr1-dev
install:
- pip install -r requirements.txt
script: true
deploy:
  provider: pypi
  user: conu-pypi-releases
  password:
    secure: tKcBpru4FPq0Pdea2xaWzpt0jPxg46gNqZ2KvORSZaEkKX8fl7yzBDDs6QoV2kH8bxK7VZni1DspPSMRN8i873hbf0hI0V3cD37EeaowEDjYQczls7qrMhuJeC/vz+QTSqbMjfcIa6oEDWZ6CiIQZ3xiSBknHeYjGVcxYTyp+9l96Ha9qyLVOWAj4LZ+QhfiqmuMSNH5tzpjTcsJrAP1gxu1dDwE9SjMMJcoeYnYcGQ1MT5yziU++TLXouW37jcBSW2o5Bnlgg7ZwyADIXTz7PSa6i/oaCtv8GgCvlb1pcKi8fYdo//JXEy6K6sqPIq+HsF/Hp9oeQ48G9HGXzeHxP6Wt7PHnclywanxJIQJ0JvhB5suvKZC82kWU/7s27RhjyqUbGxGyPGk8uC0JrOffbn0D/3bZsRVYepLhMtZbQryO8Fd+lI7AS6044ViNqZ4Eps8UlJ7SoIYPoJqwtDiCSw3Qz/E5CRzMNXwLiJi8aU+XXwTaaxi+ByBEuK70EOBdkELHtPnzELRtVRM1llQeKfy5d7lQD8zblPHTFVVM9WQeNbiujxNZ4g2OhnFlgJuSN8ui0GpioAV5owf9n8DIyBpgYRn4OgSeMbF0hJJz5mgNTB6bhtBGl/X/399gRjCPsEk9442v7XHLkVdmg3n3zH7n+SuYv8evpbou9zBsOE=
  distributions: sdist bdist_wheel
  on:
    tags: true
after_deploy:
- make check-pypi-release
